### ISSUE TITLE
hex color max length

### ISSUE THREAD

**Issue by NKjoep** [siege-media/contrast-ratio#2] opened 2012-10-22 08:11 UTC
Hi,

it would be very very handy, when writing hex colors, if the max length allowed was 7.
# XXXXXX = 7 = max allowed string ;)

**Comment by alice** [comment] 2013-03-01 18:10
Hi there,

Would you consider licensing this code as open source? I would like to re-use it in my accessibility-developer-tools library (code.google.com/p/accessibility-developer-tools, Chrome extension here: https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb), but I'm not sure what the license is.

If you'd prefer not to license it as open source, I can fall back to adding a link to your tool :) I'm also happy to make sure to credit you if I am able to use it.

Thanks, and great job!

Alice

**Comment by LeaVerou** [comment] 2013-03-01 19:48
Hi,

It’s MIT license. Feel free to send a pull request for a license file.
Of course a link to the app instead would be more appreciated :)

**Comment by mgifford** [comment] 2014-06-27 13:23
Thanks! Really appreciate this being under an open license.

**Comment by SethFalco** [comment] 2022-10-22 16:38
If this issue were to be implemented, it'd have to have a limit of 9 characters, not 7.
Hex representations of colors can include alpha. (`#RRGGBBAA`)

**Comment by LeaVerou** [comment] 2022-10-22 20:49
What is the use case for having a max length? How would it help UX?

**Comment by mgifford** [comment] 2022-10-24 13:31
Well, you'd know that you'd have implemented a valid hex value. 

Having an error message that says, "This isn't a valid hex" might also be useful.

Not sure how much this actually occurs, though.

**Comment by SethFalco** [comment] 2022-10-24 13:48
I personally don't see much use to having anything specific to hex, or putting a limit on the length of the input field. However, I do think validation and a visual cue when a malformed color is provided is nice.

I think it could be fair to close this as a duplicate of #30?

**Closed as completed** 2022-10-24 13:51 UTC
